# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MARKET_CD', models.CharField(max_length=10)),
                ('STORE_CD', models.CharField(max_length=10)),
                ('PRDT_ID', models.CharField(max_length=20)),
                ('UPC_PLU_ID', models.CharField(max_length=20)),
                ('PRICE_AMT', models.FloatField(blank=True, null=True)),
                ('PC', models.IntegerField(blank=True)),
                ('WEIGHT', models.FloatField(blank=True)),
                ('ALLERGENS', models.TextField(blank=True)),
                ('USE_YN', models.CharField(default='Y', max_length=1)),
                ('DELETE_YN', models.CharField(default='N', max_length=1)),
                ('INSERT_DATE', models.DateTimeField(auto_now_add=True)),
                ('PRDT_NAME', models.CharField(max_length=255)),
                ('SIZE_NAME', models.CharField(max_length=255)),
                ('NOTE', models.CharField(max_length=255)),
                ('PRDT_CATE_CD', models.CharField(max_length=10)),
                ('INGREDIENTS', models.TextField(blank=True)),
                ('SHELF_LIFE', models.IntegerField(default=0)),
                ('LABEL_YN', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'v10_price_info',
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('MARKET_CD', 'STORE_CD')]),
        ),
    ]
